dist: xenial
language: php
php: 
  # - '5.6'
  # - '7.1'
  - '7.2'
  #- '7.3'
  #- '7.4.22'
  
services:
# make the `mysql` binary available
  - mysql

env:
  # make environment variables available
  # bash: `$SITE_FOLDER` 
  # PHP : `getenv('SITE_FOLDER');` 
  global:
    - DB_NAME="equal"
    
before_script:
  # travis DB user is `root`, password is empty and host is `127.0.0.1`
  - mysql -e "create database IF NOT EXISTS $DB_NAME;" -uroot
  - mysql -u root -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('test');"  
  # install apache2
  - chmod +x .travis/*.sh
  - .travis/init-php7.sh
  - mkdir .packages
  - mv * ./.packages
  - mv .packages packages
  - rm -rf ./packages/.travis*
  - git clone https://github.com/cedricfrancoys/equal.git
  - mv ./equal/packages/ ./equal/packages-core
  - mv ./packages ./equal/
  - cp -r ./equal/packages-core/* ./equal/packages/
  - rm -rf ./equal/packages-core
  - mv ./equal/* ./
  - curl -O http://yb.run/discope_db.sql 
  - cat discope_db.sql | mysql -u root --password="test" $DB_NAME

script: 
  # check that mandatory directories are present and have correct access rights set
  - php run.php --do=test_fs-consistency
  # check ability to connect to the dbms service
  - php run.php --do=test_db-connectivity
  # run test units
  - php run.php --do=test_package --package=lodging 
